"use client";

import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
} from "@/components/ui/sheet";
import { Badge } from "@/components/ui/badge";
import type { ApoProposal, ApoProposalTracking } from "@/types";

function formatDateTime(dateStr: string): string {
  return new Date(dateStr).toLocaleString(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function trackingTone(status: ApoProposal["status"]) {
  if (status === "pending") return "border-amber-500/30 bg-amber-500/5";
  if (status === "approved") return "border-cyan-500/30 bg-cyan-500/5";
  return "border-emerald-500/30 bg-emerald-500/5";
}

function fallbackTracking(proposal: ApoProposal): ApoProposalTracking {
  if (proposal.status === "pending") {
    return {
      phase: "pending",
      label: "Awaiting review",
      description: "Generated by APO and waiting for operator approval.",
      timestamp: proposal.timestamp,
    };
  }
  if (proposal.status === "approved") {
    return {
      phase: "queued",
      label: "Queued for worker",
      description: "Approved and waiting for the worker.",
      timestamp: proposal.timestamp,
    };
  }
  return {
    phase: "implemented",
    label: "Archived",
    description: "Archived for audit history.",
    timestamp: proposal.timestamp,
  };
}

interface ProposalDetailProps {
  proposal: ApoProposal | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function ProposalDetail({
  proposal,
  open,
  onOpenChange,
}: ProposalDetailProps) {
  if (!proposal) return null;

  const isPending = proposal.status === "pending";
  const isApproved = proposal.status === "approved";
  const tracking = proposal.tracking ?? fallbackTracking(proposal);

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent
        side="right"
        className="border-slate-800 bg-slate-950 text-slate-100 w-[480px] sm:max-w-[480px] flex flex-col"
      >
        <SheetHeader className="pb-4 border-b border-slate-800 shrink-0">
          <div className="flex items-start gap-2 flex-wrap">
            <Badge
              variant="outline"
              className={
                isPending
                  ? "border-amber-500/50 text-amber-400 text-xs"
                  : isApproved
                    ? "border-cyan-500/50 text-cyan-400 text-xs"
                  : "border-slate-600 text-slate-400 text-xs"
              }
            >
              {isApproved ? "queued" : proposal.status}
            </Badge>
            <Badge
              variant="outline"
              className="border-slate-700 text-slate-400 text-xs"
            >
              {proposal.subsystem}
            </Badge>
          </div>
          <SheetTitle className="text-slate-100 text-base leading-snug mt-1">
            {proposal.skill}
          </SheetTitle>
          <SheetDescription className="text-slate-500 text-xs">
            {formatDateTime(proposal.timestamp)} &middot; {proposal.filename}
          </SheetDescription>
        </SheetHeader>

        <div className="flex-1 overflow-y-auto p-4 space-y-4">
          <div className={`rounded-md border p-3 ${trackingTone(proposal.status)}`}>
            <p className="text-xs font-semibold text-slate-100">{tracking.label}</p>
            <p className="mt-1 text-xs leading-relaxed text-slate-400">
              {tracking.description}
            </p>
            <dl className="mt-3 grid grid-cols-1 gap-2 text-xs sm:grid-cols-2">
              <div>
                <dt className="text-slate-500">Status time</dt>
                <dd className="text-slate-300">{formatDateTime(tracking.timestamp)}</dd>
              </div>
              {tracking.executorCli && (
                <div>
                  <dt className="text-slate-500">Executor</dt>
                  <dd className="text-slate-300">{tracking.executorCli}</dd>
                </div>
              )}
              {tracking.targetKind && (
                <div>
                  <dt className="text-slate-500">Target</dt>
                  <dd className="text-slate-300">{tracking.targetKind}</dd>
                </div>
              )}
              {tracking.applied !== undefined && (
                <div>
                  <dt className="text-slate-500">Worker result</dt>
                  <dd className="text-slate-300">
                    {tracking.applied ? "Applied" : "Already present"}
                  </dd>
                </div>
              )}
            </dl>
            {tracking.targetPath && (
              <p className="mt-3 break-all text-xs text-slate-500">{tracking.targetPath}</p>
            )}
          </div>
          <pre className="text-xs font-mono text-slate-300 whitespace-pre-wrap break-words leading-relaxed">
            {proposal.content}
          </pre>
        </div>
      </SheetContent>
    </Sheet>
  );
}
