"use client";

import type React from "react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { useApproveApoProposalMutation } from "@/lib/api-client";
import type { ApoProposal, ApoProposalTracking } from "@/types";

function formatDateTime(dateStr: string): string {
  return new Date(dateStr).toLocaleString(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function trackingTone(status: ApoProposal["status"]) {
  if (status === "pending") return "border-amber-500/30 bg-amber-500/5 text-amber-200";
  if (status === "approved") return "border-cyan-500/30 bg-cyan-500/5 text-cyan-200";
  return "border-emerald-500/30 bg-emerald-500/5 text-emerald-200";
}

function shortTarget(targetPath?: string) {
  if (!targetPath) return null;
  const parts = targetPath.split("/");
  return parts.slice(-3).join("/");
}

function fallbackTracking(proposal: ApoProposal): ApoProposalTracking {
  if (proposal.status === "pending") {
    return {
      phase: "pending",
      label: "Awaiting review",
      description: "Generated by APO and waiting for operator approval.",
      timestamp: proposal.timestamp,
    };
  }
  if (proposal.status === "approved") {
    return {
      phase: "queued",
      label: "Queued for worker",
      description: "Approved and waiting for the worker.",
      timestamp: proposal.timestamp,
    };
  }
  return {
    phase: "implemented",
    label: "Archived",
    description: "Archived for audit history.",
    timestamp: proposal.timestamp,
  };
}

interface ProposalCardProps {
  proposal: ApoProposal;
  onClick: (proposal: ApoProposal) => void;
}

export function ProposalCard({ proposal, onClick }: ProposalCardProps) {
  const isPending = proposal.status === "pending";
  const isApproved = proposal.status === "approved";
  const tracking = proposal.tracking ?? fallbackTracking(proposal);
  const preview = proposal.content.slice(0, 200).replace(/#+\s/g, "").trim();
  const approveProposal = useApproveApoProposalMutation();

  function handleApprove(event: React.MouseEvent<HTMLButtonElement>) {
    event.stopPropagation();
    approveProposal.mutate(proposal.id);
  }

  return (
    <Card
      className={[
        "border-slate-800 bg-slate-900/50 p-4 cursor-pointer transition-colors",
        "hover:border-slate-700 hover:bg-slate-800/60",
        isPending ? "border-l-2 border-l-amber-500" : "",
        isApproved ? "border-l-2 border-l-cyan-500" : "",
      ].join(" ")}
      onClick={() => onClick(proposal)}
    >
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="font-semibold text-slate-100 text-sm truncate">
              {proposal.skill}
            </span>
            <Badge
              variant="outline"
              className={
                isPending
                  ? "border-amber-500/50 text-amber-400 text-xs"
                  : isApproved
                    ? "border-cyan-500/50 text-cyan-400 text-xs"
                  : "border-slate-600 text-slate-400 text-xs"
              }
            >
              {isApproved ? "queued" : proposal.status}
            </Badge>
          </div>
          <p className="text-xs text-slate-500 mt-0.5">
            subsystem: <span className="text-slate-400">{proposal.subsystem}</span>
          </p>
          <p className="text-xs text-slate-500 mt-0.5">
            {formatDateTime(proposal.timestamp)}
          </p>
          <div
            className={[
              "mt-3 rounded-md border px-3 py-2",
              trackingTone(proposal.status),
            ].join(" ")}
          >
            <div className="flex items-center justify-between gap-2">
              <p className="text-xs font-semibold">{tracking.label}</p>
              <p className="text-[11px] text-slate-400">
                {formatDateTime(tracking.timestamp)}
              </p>
            </div>
            <p className="mt-1 text-xs text-slate-400">{tracking.description}</p>
            {(tracking.executorCli || tracking.targetKind || tracking.applied !== undefined) && (
              <div className="mt-2 flex flex-wrap gap-2 text-[11px] text-slate-400">
                {tracking.executorCli && <span>executor: {tracking.executorCli}</span>}
                {tracking.targetKind && <span>target: {tracking.targetKind}</span>}
                {tracking.applied !== undefined && (
                  <span>{tracking.applied ? "applied" : "already present"}</span>
                )}
              </div>
            )}
            {tracking.targetPath && (
              <p className="mt-1 truncate text-[11px] text-slate-500">
                {shortTarget(tracking.targetPath)}
              </p>
            )}
          </div>
          <p className="text-xs text-slate-400 mt-2 line-clamp-3 leading-relaxed">
            {preview}
            {proposal.content.length > 200 && "…"}
          </p>
          {approveProposal.isError && (
            <p className="mt-2 text-xs text-rose-400">
              {approveProposal.error instanceof Error
                ? approveProposal.error.message
                : "Approval failed"}
            </p>
          )}
        </div>
        {isPending && (
          <button
            type="button"
            onClick={handleApprove}
            disabled={approveProposal.isPending}
            className="shrink-0 rounded-md border border-emerald-500/50 bg-emerald-500/10 px-3 py-1.5 text-xs font-semibold text-emerald-300 transition-colors hover:border-emerald-400 hover:bg-emerald-500/20 disabled:cursor-not-allowed disabled:opacity-50"
          >
            {approveProposal.isPending ? "Approving…" : "Approve"}
          </button>
        )}
      </div>
    </Card>
  );
}
